#!/usr/bin/env php
<?php
print json_encode(array_combine(
    get_defined_functions()["internal"],
    array_map(function($n) {
        return array_map(
            function($p) {return $p->isPassedByReference();},
            (new ReflectionFunction($n))->getParameters()
        );
    }, get_defined_functions()["internal"])
), JSON_PRETTY_PRINT);